apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: balcerski-eu-tls
spec:
  secretName: balcerski-eu
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: balcerski.eu
  dnsNames:
    - balcerski.eu
    - www.balcerski.eu